spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000
  cors:
      allowedOrigin: ${CORS_ALLOWED_ORIGIN}
      allowedMethod: ${CORS_ALLOWED_METHOD}
      allowedHeader: ${CORS_ALLOWED_HEADER}

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    root: info
    liquibase: error

exception:
  handling:
    include: true

server:
  port: 8081
